<map id="openage::pyinterface::PyException::type_name" name="openage::pyinterface::PyException::type_name">
<area shape="rect" id="node2" href="$d1/d18/namespaceopenage_1_1pyinterface_1_1tests.xhtml#a1e06395c26a8fbab8f488d6e573cde6b" title="openage::pyinterface\l::tests::err_py_to_cpp" alt="" coords="232,5,381,47"/>
<area shape="rect" id="node3" href="$d1/d18/namespaceopenage_1_1pyinterface_1_1tests.xhtml#a0f930d1710b53aa90f3e05e85aa5d544" title="openage::pyinterface\l::tests::pyobject_demo" alt="" coords="229,71,384,112"/>
</map>
